SET SCHEMA FN24_3MI0700035;

-- T01
CREATE OR REPLACE FUNCTION EMP_AGE(EMP_NO CHAR(6))
    RETURNS INT
    SPECIFIC EMP_AGE
    RETURN SELECT YEAR(CURRENT_DATE - BIRTHDATE) AS AGE
           FROM DB2SAMPLE.EMP
           WHERE EMPNO = EMP_NO;


-- T02
CREATE OR REPLACE FUNCTION EMP_EXPERIENCE(EMP_NO CHAR(6))
    RETURNS INT
    SPECIFIC EMP_EXPERIENCE
    RETURN SELECT YEAR(CURRENT_DATE - HIREDATE) AS EXPERIENCE
           FROM DB2SAMPLE.EMP
           WHERE EMPNO = EMP_NO;

-- T03
CREATE OR REPLACE FUNCTION EMP_LNAME_SAL(EMP_NO CHAR(6))
    RETURNS TABLE
            (
                LNAME  VARCHAR(15),
                SALARY DEC
            )
    SPECIFIC EMP_LNAME_SAL
    RETURN SELECT LASTNAME, SALARY
           FROM DB2SAMPLE.EMP E
           WHERE E.EMPNO = EMP_NO;

-- T04
