SET SCHEMA FN24_3MI0700035;
INSERT INTO EMPLOYEE
SELECT *
FROM DB2SAMPLE.EMPLOYEE;

-- TASK01
SELECT *
FROM EMPLOYEE
WHERE HIREDATE <= BIRTHDATE + 18 YEARS;

CREATE OR REPLACE PROCEDURE CORRECT_HIREDATE(IN EMP_ID INT)
BEGIN
    FOR E AS E1 CURSOR FOR (SELECT HIREDATE, BIRTHDATE FROM EMPLOYEE E WHERE EMPNO = EMP_ID)
        DO
            IF (E.HIREDATE <= (E.BIRTHDATE + 18 YEARS))
            THEN
                UPDATE EMPLOYEE
                SET HIREDATE = CURRENT_DATE
                WHERE EMPNO = EMP_ID;
                CALL DBMS_OUTPUT.PUT_LINE('HERE');
            END IF;
        end for;
end;

BEGIN
    FOR E AS E1 CURSOR FOR (SELECT EMPNO FROM EMPLOYEE)
        DO
            CALL FN24_3MI0700035.CORRECT_HIREDATE(E.EMPNO);
        end for;
end;

-- TASK02
DELETE
FROM PROJECT;
INSERT INTO PROJECT
SELECT *
FROM DB2SAMPLE.PROJECT;

CREATE OR REPLACE PROCEDURE CORRECT_PRENDATE()
BEGIN
    FOR P AS P1 CURSOR FOR (SELECT PRENDATE, PRSTDATE, PROJNO FROM PROJECT)
        DO
            IF (P.PRSTDATE < P.PRENDATE)
            THEN
                UPDATE PROJECT
                SET PRENDATE = NULL
                WHERE PROJNO = P.PROJNO;
                CALL DBMS_OUTPUT.PUT_LINE('HERE');
            END IF;
        end for;
end;
BEGIN
    CALL FN24_3MI0700035.CORRECT_PRENDATE();
end;

-- TASK03
SELECT *
FROM DEPARTMENT;

CREATE OR REPLACE PROCEDURE GET_DEPT_INFO(IN DEPT_ID CHARACTER(3))
BEGIN
    FOR E AS E1 CURSOR FOR (SELECT EMPNO,
                                   (FIRSTNME || ' ' || LASTNAME)                                 AS FULLNAME,
                                   (COALESCE(SALARY, 0) + COALESCE(BONUS, 0)+ COALESCE(COMM, 0)) AS INCOME
                            FROM EMPLOYEE
                            WHERE WORKDEPT = DEPT_ID)
        DO
            CALL DBMS_OUTPUT.PUT_LINE('ID: ' || E.EMPNO || ', NAME: ' || E.FULLNAME || ', INCOME: ' || E.INCOME);
        end for;
end;

BEGIN
    CALL FN24_3MI0700035.GET_DEPT_INFO('C01');
end;

-- TASK04
