SET SCHEMA FN24_3MI0700035;

SELECT *
FROM DB2INST1.EMPLOYEE;

CREATE TABLE DB2INST_EMPLOYEE LIKE DB2INST1.EMPLOYEE;
ALTER TABLE DB2INST_EMPLOYEE
    ADD PRIMARY KEY (EMPNO);


INSERT INTO DB2INST_EMPLOYEE
SELECT *
FROM DB2INST1.EMPLOYEE
WHERE SEX = 'M';
SELECT *
FROM DB2INST_EMPLOYEE;

SET SCHEMA FN24_3MI0700035;

CREATE OR REPLACE FUNCTION DEPT_EMP_CNT(DEPT_ID CHARACTER(3))
    RETURNS INT
    RETURN SELECT COUNT(EMPNO)
           FROM DB2INST_EMPLOYEE
           WHERE WORKDEPT = DEPT_ID;

VALUES (FN24_3MI0700035.DEPT_EMP_CNT('A00'));


SET SCHEMA FN24_3MI0700035;

CREATE OR REPLACE TRIGGER TRIG_EMP_INC_SAL_ON_HIREDATE_CHANGE
    BEFORE UPDATE OF HIREDATE
    ON DB2INST_EMPLOYEE
    REFERENCING OLD AS O NEW AS N
    FOR EACH ROW
    WHEN ( O.HIREDATE != N.HIREDATE AND O.SALARY >= N.SALARY)
    SET N.SALARY = N.SALARY + 1000;

SELECT EMPNO,SALARY FROM DB2INST_EMPLOYEE WHERE EMPNO = '000020';
UPDATE DB2INST_EMPLOYEE SET HIREDATE = CURRENT_DATE
WHERE EMPNO = '000020';
SELECT EMPNO,SALARY FROM DB2INST_EMPLOYEE WHERE EMPNO = '000020';


SELECT *
FROM TABLE(DB2INST1.EXAM('FN24_3MI0700035')) T
WHERE DATE(T.CTIME) = CURRENT_DATE
ORDER BY T.CTIME DESC;