SET SCHEMA FN24_3MI0700035;

CREATE TABLE DEPARTMENTS LIKE DB2HR.DEPARTMENTS;
CREATE TABLE EMPLOYEES LIKE DB2HR.EMPLOYEES;
CREATE TABLE JOBS LIKE DB2HR.JOBS;
CREATE TABLE JOB_HISTORY LIKE DB2HR.JOB_HISTORY;
CREATE TABLE LOCATIONS LIKE DB2HR.LOCATIONS;
CREATE TABLE COUNTRIES LIKE DB2HR.COUNTRIES;
CREATE TABLE REGIONS LIKE DB2HR.REGIONS;


ALTER TABLE JOBS ADD PRIMARY KEY (JOB_ID);
INSERT INTO JOBS SELECT * FROM DB2HR.JOBS;

ALTER TABLE REGIONS ADD PRIMARY KEY (REGION_ID);
INSERT INTO REGIONS SELECT * FROM DB2HR.REGIONS;

ALTER TABLE COUNTRIES ADD PRIMARY KEY (COUNTRY_ID);
ALTER TABLE COUNTRIES ADD FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID);
INSERT INTO COUNTRIES SELECT * FROM DB2HR.COUNTRIES;

ALTER TABLE LOCATIONS ADD PRIMARY KEY (LOCATION_ID);
ALTER TABLE LOCATIONS ADD FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID);
INSERT INTO LOCATIONS SELECT * FROM DB2HR.LOCATIONS;

ALTER TABLE DEPARTMENTS ADD PRIMARY KEY (DEPARTMENT_ID);
ALTER TABLE DEPARTMENTS ADD FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID);
INSERT INTO DEPARTMENTS SELECT * FROM DB2HR.DEPARTMENTS;

ALTER TABLE EMPLOYEES ADD PRIMARY KEY (EMPLOYEE_ID);
ALTER TABLE EMPLOYEES ADD FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);
ALTER TABLE EMPLOYEES ADD FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID);
ALTER TABLE EMPLOYEES ADD FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID);
INSERT INTO EMPLOYEES SELECT * FROM DB2HR.EMPLOYEES;

ALTER TABLE JOB_HISTORY ADD FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID);
ALTER TABLE JOB_HISTORY ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);
ALTER TABLE JOB_HISTORY ADD FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID);
INSERT INTO JOB_HISTORY SELECT * FROM DB2HR.JOB_HISTORY;

