SET SCHEMA FN3MI0700035;

CREATE OR REPLACE TRIGGER TRIG_VALIDATE_RETAKE
    BEFORE INSERT
    ON TAKESEXAM
    REFERENCING NEW AS N
    FOR EACH ROW
    WHEN (EXISTS (SELECT *
                  FROM TAKENEXAMS
                  WHERE FN = N.FN
                    AND NEXAM = N.NEXAM))
BEGIN
    SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Student has already taken this exam';
end;

INSERT INTO TAKESEXAM (FN, NEXAM, DATE)
VALUES ('AB456CD789', 9, CURRENT_DATE);

CREATE OR REPLACE TRIGGER TRIG_FIX_EXAM_POINTS
    BEFORE UPDATE
    ON EXAMS
    REFERENCING NEW AS N
    FOR EACH ROW
BEGIN
    DECLARE EXAM_POINTS REAL;
    CALL FN3MI0700035.PROC_CALC_EXAM_POINTS(N.NEXAM, EXAM_POINTS);
    IF (EXAM_POINTS != N.MAXPOINTS)
    THEN
        SET N.MAXPOINTS = EXAM_POINTS;
    end if;
end;