SET SCHEMA FN24_3MI0700035;

-- T01
CREATE OR REPLACE FUNCTION IS_ODD(num INT)
    RETURNS SMALLINT
    LANGUAGE SQL
BEGIN
    IF MOD(num, 2) = 0
    THEN
        RETURN 0;
    ELSE
        RETURN 1;
    END IF;
END;

SELECT 2 AS NUM, FN24_3MI0700035.IS_ODD(2) AS IS_ODD
FROM SYSIBM.SYSDUMMY1;

-- T02
CREATE MODULE MOD2;

ALTER MODULE MOD2 PUBLISH VARIABLE TEST INT;
SET SCHEMA FN24_3MI0700035;

ALTER MODULE MOD2 PUBLISH FUNCTION AVG_SALARY_DEPT(DEPT INT)
    RETURNS DECIMAL
    LANGUAGE SQL
BEGIN
    DECLARE RESULT DEC;
    SET SCHEMA DB2HR;
    SET RESULT = (SELECT DECIMAL(AVG(SALARY), 10, 2)
                  FROM DB2HR.EMPLOYEES
                  WHERE DEPARTMENT_ID = DEPT
                  GROUP BY DEPARTMENT_ID);
    SET SCHEMA FN24_3MI0700035;
    RETURN RESULT;
end;

SELECT 100 AS DEPT, FN24_3MI0700035.MOD2.AVG_SALARY_DEPT(100) AS AVG
FROM SYSIBM.SYSDUMMY1;

ALTER MODULE MOD2 DROP PROCEDURE DEPT_INFO(INT);
ALTER MODULE MOD2 PUBLISH PROCEDURE DEPT_INFO(IN DEPT INT)
    LANGUAGE SQL
BEGIN
    DECLARE NAME VARCHAR(30);
    DECLARE MIN_SAL DEC;
    DECLARE MAX_SAL DEC;
    DECLARE AVG_SAL DEC;
    SET (NAME, MIN_SAL, MAX_SAL, AVG_SAL) =
            (SELECT D.DEPARTMENT_NAME, MIN(E.SALARY), MAX(E.SALARY), DEC(AVG(E.SALARY), 10, 2)
             FROM DB2HR.EMPLOYEES E
                      JOIN DB2HR.DEPARTMENTS D on D.DEPARTMENT_ID = E.DEPARTMENT_ID
             WHERE E.DEPARTMENT_ID = DEPT
               AND E.SALARY > FN24_3MI0700035.MOD2.AVG_SALARY_DEPT(DEPT)
             GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME);

    CALL DBMS_OUTPUT.PUT_LINE('NAME: ' || NAME || ' MIN: ' || MIN_SAL || ' MAX: ' || MAX_SAL || ' AVG: ' || AVG_SAL);

end;

BEGIN
    CALL FN24_3MI0700035.MOD2.DEPT_INFO(90);
end;

