SET SCHEMA DB2SAMPLE;

-- T01
SELECT EMPNO, LASTNAME, BIRTHDATE, SALARY
FROM EMP
WHERE SALARY > 30000
ORDER BY SALARY DESC;

--T02
SELECT LASTNAME, FIRSTNME, WORKDEPT
FROM EMP
ORDER BY WORKDEPT DESC, LASTNAME DESC;

--T03
SELECT DISTINCT EDLEVEL
FROM EMP
ORDER BY EDLEVEL;

--T04
SELECT DISTINCT *
FROM EMP_ACT
WHERE EMPNO <= 100
ORDER BY EMPNO;

--T05
SELECT LASTNAME, SALARY, BONUS
FROM EMP
WHERE SEX = 'M';

--T06
SELECT LASTNAME, SALARY, COMM
FROM EMP
WHERE SALARY > 20000
  AND YEAR(HIREDATE) > 1979;

--T07
SELECT LASTNAME, SALARY, BONUS, COMM
FROM EMP
WHERE (SALARY > 22000 AND BONUS = 400)
   OR (BONUS = 500 AND COMM < 1900)
ORDER BY LASTNAME;

--T08
SELECT LASTNAME, SALARY, BONUS, COMM
FROM EMP
WHERE SALARY > 22000
  AND COMM < 1900
  AND (BONUS = 400 OR BONUS = 500)
ORDER BY LASTNAME;

--T09
SELECT PROJNO, ACTNO, EMSTDATE, EMENDATE
FROM EMP_ACT
WHERE PROJNO LIKE 'AD%'
  AND (ACTNO = 10 OR ACTNO = 80 OR ACTNO = 180)
ORDER BY ACTNO;

--T10
SELECT MGRNO, DEPTNO
FROM DEPARTMENT
WHERE MGRNO IS NOT NULL
ORDER BY MGRNO;

--T11
SELECT EMPNO, LASTNAME, SALARY, BONUS
FROM EMP
WHERE BONUS >= 800
  AND BONUS <= 1000
ORDER BY BONUS, EMPNO;

--T12
SELECT EMPNO, LASTNAME, SALARY, WORKDEPT
FROM EMP
WHERE WORKDEPT >= 'A00'
  AND WORKDEPT <= 'C01'
ORDER BY LASTNAME, EMPNO;

--T13
SELECT *
FROM PROJECT
WHERE UPPER(PROJNAME) LIKE '%SUPPORT%'
ORDER BY PROJNO;

--T14
SELECT *
FROM DEPARTMENT
WHERE DEPTNO LIKE '%_1_%'
ORDER BY DEPTNO;

--T15
SELECT DISTINCT LASTNAME, FIRSTNME, MIDINIT, SALARY
FROM EMP
WHERE JOB != 'PRES'
  AND JOB != 'MANAGER'
ORDER BY SALARY
    FETCH FIRST 5 ROWS ONLY;
