SET SCHEMA FN24_3MI0700035;

-- TASK01
CREATE OR REPLACE PROCEDURE PRINT_HELLO(IN name VARCHAR(100))
    LANGUAGE SQL
BEGIN

    CALL DBMS_OUTPUT.PUT_LINE('Hello, ' || name || '!');
END;

CALL FN24_3MI0700035.PRINT_HELLO('GOSHO');

CREATE OR REPLACE PROCEDURE SQRT_OF_SUM(IN lval DECIMAL, IN rval DECIMAL)
    LANGUAGE SQL
BEGIN
    DECLARE RESULT DECIMAL;
    SET RESULT = SQRT(lval + rval);

    CALL DBMS_OUTPUT.PUT_LINE('SQRT: ' || RESULT || ' OF SUM: ' || (lval + rval));
END;

CALL  FN24_3MI0700035.SQRT_OF_SUM(4,5)