SET SCHEMA FN24_3MI0700035;


CREATE OR REPLACE PROCEDURE PRINT_HELLO(IN name VARCHAR(100))
LANGUAGE SQL
BEGIN

    CALL DBMS_OUTPUT.PUT_LINE('Hello, ' || name || '!');
END;

CALL FN3MI0700035.PRINT_HELLO('GOSHO');