SET SCHEMA FN24_3MI0700035;

-- TASK01
CREATE OR REPLACE PROCEDURE PRINT_HELLO(IN name VARCHAR(100))
    LANGUAGE SQL
BEGIN

    CALL DBMS_OUTPUT.PUT_LINE('Hello, ' || name || '!');
END;

CALL FN24_3MI0700035.PRINT_HELLO('GOSHO');

CREATE OR REPLACE PROCEDURE SQRT_OF_SUM(IN lval DECIMAL, IN rval DECIMAL)
    LANGUAGE SQL
BEGIN
    DECLARE RESULT DECIMAL;
    SET RESULT = SQRT(lval + rval);

    CALL DBMS_OUTPUT.PUT_LINE('SQRT: ' || RESULT || ' OF SUM: ' || (lval + rval));
END;

CALL FN24_3MI0700035.SQRT_OF_SUM(4, 5)

SET SCHEMA FN24_3MI0700035;
CREATE OR REPLACE PROCEDURE P3_FOO(OUT P_DAY INT)
    LANGUAGE SQL
BEGIN
    DECLARE V_DATE DATE;
    SET V_DATE = CURRENT_DATE;
    SET P_DAY = DAYOFYEAR(V_DATE);
END;

BEGIN
    DECLARE DAY INT;
    SET DAY = 12;
    CALL FN24_3MI0700035.P3_FOO(DAY);
    CALL DBMS_OUTPUT.PUT_LINE(DAY);
END;

CREATE OR REPLACE PROCEDURE GET_DAY_OF_YEAR(IN DATE_PARAM DATE)
BEGIN
    CALL DBMS_OUTPUT.PUT_LINE(JULIAN_DAY(DATE_PARAM) || ' ' || DAYNAME(DATE_PARAM) || ' ' || DAYOFYEAR(DATE_PARAM));
END;

CALL FN24_3MI0700035.GET_DAY_OF_YEAR('2002-11-15');

CREATE OR REPLACE MODULE MOD1;
BEGIN
ALTER MODULE MOD1
    DROP PROCEDURE PITAGOR;
ALTER MODULE MOD1 PUBLISH PROCEDURE
    PITAGOR(IN P_A DECIMAL(9, 2), IN P_B DECIMAL(9, 2), OUT OUTPUT DECIMAL(9, 2))
BEGIN
    SET OUTPUT = SQRT(P_A*P_A+P_B*P_B);
END;
END;
BEGIN
    DECLARE OUTPUT DEC(9,2);
    CALL FN24_3MI0700035.MOD1.PITAGOR(2,4,OUTPUT);
    CALL DBMS_OUTPUT.PUT_LINE(OUTPUT);
end;

CREATE OR REPLACE FUNCTION F_PITAGOR(P_A DECIMAL(9,2),P_B DECIMAL(9,2))
RETURNS DEC(9,2)
RETURN SQRT(P_A*P_A+P_B*P_B);


SELECT FN24_3MI0700035.MOD1.F_PITAGOR(2,4) FROM SYSIBM.SYSDUMMY1;
VALUES FN24_3MI0700035.MOD1.F_PITAGOR(2,4);

DROP FUNCTION F_PITAGOR;
ALTER MODULE MOD1 PUBLISH FUNCTION
    F_PITAGOR(P_A DECIMAL(9,2),P_B DECIMAL(9,2))
RETURNS DEC(9,2)
RETURN SQRT(P_A*P_A+P_B*P_B);