SET SCHEMA DB2SAMPLE;

-- T01
SELECT LASTNAME, FIRSTNME, DEPT.DEPTNAME
FROM EMP
         JOIN DEPT ON DEPT.DEPTNO = EMP.WORKDEPT
ORDER BY DEPT.DEPTNAME, LASTNAME, FIRSTNME;
-- TODO  Sequence the report on first name within last name, within department
--  name.

-- T02
SELECT LASTNAME, FIRSTNME, JOB, DEPT.DEPTNAME
FROM EMP
         JOIN DEPT ON DEPT.DEPTNO = EMP.WORKDEPT
WHERE WORKDEPT >= 'A02'
  AND WORKDEPT <= 'D22'
  AND JOB != 'MANAGER'
ORDER BY DEPT.DEPTNAME, JOB, LASTNAME, FIRSTNME;

-- T03
SELECT DEPTNAME, (EMP.LASTNAME || ' ' || EMP.FIRSTNME) AS MANAGER_NAME
FROM DEPT
         JOIN EMP ON EMP.EMPNO = DEPT.MGRNO
ORDER BY DEPTNAME;

-- T04
SELECT DEPTNAME, (LASTNAME || ' ' || FIRSTNME) AS MANAGER_NAME
FROM EMP
         JOIN DEPT ON EMP.WORKDEPT = DEPT.DEPTNO
WHERE JOB = 'MANAGER'
ORDER BY DEPTNAME;

-- NOT SAME, Presidents are managers too

-- T05
SELECT DISTINCT PROJ.PROJNO, PROJNAME, EMP_ACT.ACTNO
FROM PROJ
         JOIN EMP_ACT ON PROJ.PROJNO = EMP_ACT.PROJNO
WHERE PROJ.PROJNO LIKE 'AD%'
ORDER BY PROJ.PROJNO, ACTNO;

-- T06
SELECT DISTINCT EMP.EMPNO, LASTNAME, PROJNO
FROM EMP
         JOIN EMPACT ON EMPACT.EMPNO = EMP.EMPNO
WHERE EMPACT.PROJNO = 'AD3113'
ORDER BY EMPNO, PROJNO;

-- T07
SELECT DISTINCT EMPNO, EMPACT.PROJNO, PROJ.PROJNAME, ACTNO, EMSTDATE
FROM EMPACT
         JOIN PROJ ON PROJ.PROJNO = EMPACT.PROJNO
WHERE EMSTDATE = '2002-01-01'
ORDER BY EMPACT.PROJNO, EMPNO, ACTNO;

-- T08
SELECT DISTINCT WORKDEPT, LASTNAME, PROJNAME, EMPACT.ACTNO
FROM EMP
         JOIN (SELECT ACTNO, EMPNO, PROJ.PROJNAME
               FROM EMPACT
                        JOIN PROJ ON PROJ.PROJNO = EMPACT.PROJNO) AS EMPACT ON EMPACT.EMPNO = EMP.EMPNO
WHERE WORKDEPT = 'A00'
ORDER BY PROJNAME, ACTNO;

-- T09
SELECT DISTINCT WORKDEPT, LASTNAME, PROJNAME, EMPACT.ACTNO
FROM EMP
         JOIN (SELECT ACTNO, EMPNO, PROJ.PROJNAME
               FROM EMPACT
                        JOIN PROJ ON PROJ.PROJNO = EMPACT.PROJNO) AS EMPACT ON EMPACT.EMPNO = EMP.EMPNO
WHERE WORKDEPT >= 'A00'
  AND WORKDEPT <= 'C01'
ORDER BY WORKDEPT, LASTNAME, ACTNO;

SELECT *
FROM EMPACT;
-- T10
SELECT DISTINCT ACTNO, EMPACT.EMPNO, PROJ.MGRNO, EMSTDATE, EMPACT.PROJNO, LASTNAME
FROM EMPACT
         JOIN EMP ON EMP.EMPNO = EMPACT.EMPNO
         JOIN (SELECT PROJNO, DEPT.MGRNO
               FROM PROJ
                        JOIN DEPT ON DEPT.DEPTNO = PROJ.DEPTNO) AS PROJ ON PROJ.PROJNO = EMPACT.PROJNO
WHERE EMSTDATE = '2002-10-15'
ORDER BY ACTNO, EMSTDATE;

-- T11
SELECT DISTINCT EMP.WORKDEPT,
                MNGR.LASTNAME AS MANAGER_LASTNAME,
                EMP.LASTNAME  AS EMPLOYEE_LASTNAME,
                MNGR.HIREDATE AS MANAGER_HIREDATE,
                EMP.HIREDATE  AS EMPLOYEE_HIREDATE
FROM EMP
         JOIN DEPT ON DEPT.DEPTNO = EMP.WORKDEPT
         JOIN (SELECT LASTNAME, HIREDATE, EMPNO
               FROM EMP) AS MNGR ON MNGR.EMPNO = DEPT.MGRNO
WHERE EMP.WORKDEPT = 'A00'
  AND EMP.EMPNO != MNGR.EMPNO
ORDER BY EMP.LASTNAME;