SET SCHEMA DB2SAMPLE;

-- TASK01
SELECT LASTNAME, SALARY, (SALARY * 1.05) AS "INC-Y-SALARY", DECIMAL((SALARY / 12.0 * 1.05), 10, 2) AS "INC-M-SALARY"
FROM EMP
WHERE (SALARY * 1.05) <= 40000
ORDER BY SALARY DESC;

-- TASK02
SELECT LASTNAME,
       EDLEVEL,
       (SALARY + 1200)                    AS NEW_SALARY,
       COALESCE(DEC(BONUS / 2, 10, 2), 0) AS NEW_BONUS
FROM EMP
WHERE EDLEVEL = 18
   OR EDLEVEL = 20
ORDER BY EDLEVEL DESC, NEW_SALARY DESC;

-- TASK03
SELECT WORKDEPT, LASTNAME, (SALARY - 1000) AS DECR_SALARY
FROM EMP
WHERE WORKDEPT = 'D11'
  AND SALARY BETWEEN 0.8 * 20000 AND 3 * 20000
ORDER BY DECR_SALARY DESC;

-- TASK04
SELECT WORKDEPT, LASTNAME, (COALESCE(SALARY, 0) + COALESCE(COMM, 0) + COALESCE(BONUS, 0)) AS INCOME
FROM EMP
WHERE WORKDEPT = 'D11'
  AND SALARY * 1.1 > (COALESCE(SALARY, 0) + COALESCE(COMM, 0) + COALESCE(BONUS, 0))
ORDER BY INCOME DESC;

-- TASK05
SELECT DEPTNO, DEPTNAME, COALESCE(MGRNO, 'UNKNOWN') AS MGRNO
FROM DEPT
WHERE MGRNO IS NULL;

-- TASK06
SELECT PROJNO, COALESCE(MAJPROJ, 'MAIN PROJECT') AS "MAJOR PROJECT"
FROM PROJ
WHERE PROJNO LIKE 'MA%'
ORDER BY PROJNO;

-- TASK07
SELECT EMPNO, LASTNAME, YEAR(HIREDATE - BIRTHDATE) AS AGE
FROM EMP
WHERE YEAR(HIREDATE - BIRTHDATE) <= 25
ORDER BY AGE, EMPNO;

-- TASK08
SELECT YEAR(PRSTDATE) AS YEAR, MONTH(PRSTDATE), PROJNO AS MONTH
FROM PROJ
WHERE PRENDATE = DATE('2003-02-01')
ORDER BY PROJNO;

-- TASK09
SELECT PROJNO, (DAYS(PRENDATE) - DAYS(PRSTDATE)) / 7 AS WEEKS, PRENDATE, PRSTDATE
FROM PROJ
ORDER BY PROJNO;

-- TASK10
SELECT PROJNO, PRENDATE AS ESTIMATED, ADD_MONTHS(PRENDATE, (MONTHS_BETWEEN(PRENDATE, PRSTDATE) * 0.1)) AS EXPECTED
FROM PROJ
WHERE PROJNO LIKE 'MA%'
ORDER BY PROJNO;

-- TASK11
SELECT DAYS(DATE('2000-01-01')) - DAYS(DATE('1969-07-20')) AS DAYS
FROM SYSIBM.SYSDUMMY1;