SET SCHEMA FN3MI0700035;

CREATE OR REPLACE FUNCTION FUNC_HAS_PASSED_EXAM(student_fn CHAR(10), exam_id INT)
    RETURNS SMALLINT
    LANGUAGE SQL
BEGIN
    DECLARE grade REAL;

    SELECT GRADE
    INTO grade
    FROM TAKENEXAMS
    WHERE FN = student_fn
      AND NEXAM = exam_id;

    RETURN CASE WHEN grade > 2 THEN 1 ELSE 0 end;
END;

VALUES (FN3MI0700035.FUNC_HAS_PASSED_EXAM('AB456CD789', 8)); -- 0
VALUES (FN3MI0700035.FUNC_HAS_PASSED_EXAM('AB456CD789', 11)); -- 1

CREATE OR REPLACE FUNCTION FUNC_AVG_GRADE_STUDENT(student_fn CHAR(10))
RETURNS REAL
BEGIN
    DECLARE avg_grade REAL;

    SELECT AVG(GRADE) INTO avg_grade
    FROM TAKENEXAMS
    WHERE FN = student_fn;

    RETURN avg_grade;
END;

VALUES(FN3MI0700035.FUNC_AVG_GRADE_STUDENT('AB456CD789')); -- 5