SET SCHEMA FN24_3MI0700035;

CREATE TABLE DEPARTMENTS LIKE DB2HR.DEPARTMENTS;
CREATE TABLE EMPLOYEES LIKE DB2HR.EMPLOYEES;
CREATE TABLE JOBS LIKE DB2HR.JOBS;
CREATE TABLE JOB_HISTORY LIKE DB2HR.JOB_HISTORY;
CREATE TABLE LOCATIONS LIKE DB2HR.LOCATIONS;
CREATE TABLE COUNTRIES LIKE DB2HR.COUNTRIES;
CREATE TABLE REGIONS LIKE DB2HR.REGIONS;


ALTER TABLE JOBS ADD PRIMARY KEY (JOB_ID);
INSERT INTO JOBS SELECT * FROM DB2HR.JOBS;

ALTER TABLE REGIONS ADD PRIMARY KEY (REGION_ID);
INSERT INTO REGIONS SELECT * FROM DB2HR.REGIONS;

ALTER TABLE COUNTRIES ADD PRIMARY KEY (COUNTRY_ID);
ALTER TABLE COUNTRIES ADD FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID);
INSERT INTO COUNTRIES SELECT * FROM DB2HR.COUNTRIES;

ALTER TABLE LOCATIONS ADD PRIMARY KEY (LOCATION_ID);
ALTER TABLE LOCATIONS ADD FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID);
INSERT INTO LOCATIONS SELECT * FROM DB2HR.LOCATIONS;

ALTER TABLE DEPARTMENTS ADD PRIMARY KEY (DEPARTMENT_ID);
ALTER TABLE DEPARTMENTS ADD FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID);
INSERT INTO DEPARTMENTS SELECT * FROM DB2HR.DEPARTMENTS;

ALTER TABLE EMPLOYEES ADD PRIMARY KEY (EMPLOYEE_ID);
ALTER TABLE EMPLOYEES ADD FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);
ALTER TABLE EMPLOYEES ADD FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID);
ALTER TABLE EMPLOYEES ADD FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID);
INSERT INTO EMPLOYEES SELECT * FROM DB2HR.EMPLOYEES;

ALTER TABLE JOB_HISTORY ADD FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID);
ALTER TABLE JOB_HISTORY ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);
ALTER TABLE JOB_HISTORY ADD FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID);
INSERT INTO JOB_HISTORY SELECT * FROM DB2HR.JOB_HISTORY;


CREATE OR REPLACE PROCEDURE GET_EMP_INFO(IN EMP_ID INTEGER)
BEGIN
    DECLARE EMP_FULLNAME VARCHAR(45);
    DECLARE DEPT_ID INTEGER;
    DECLARE EMP_SALARY DECIMAL(8, 2);
    DECLARE DEPT_NAME VARCHAR(30);
    DECLARE JOB VARCHAR(10);
    DECLARE MIN_SALARY DEC(9, 2);
    DECLARE MAX_SALARY DEC(9, 2);
    SET (EMP_FULLNAME, EMP_SALARY, DEPT_NAME, DEPT_ID, MIN_SALARY, MAX_SALARY, JOB) =
            (SELECT (FIRST_NAME || ' ' || LAST_NAME),
                    SALARY,
                    D.DEPARTMENT_NAME,
                    D.DEPARTMENT_ID,
                    J.MIN_SALARY,
                    J.MAX_SALARY,
                    J.JOB_ID
             FROM EMPLOYEES E
                      JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
                      JOIN JOBS J ON J.JOB_ID = E.JOB_ID
             WHERE E.EMPLOYEE_ID = EMP_ID);

    CALL DBMS_OUTPUT.PUT_LINE('NAME: ' || EMP_FULLNAME || ', EMP_SALARY: ' || EMP_SALARY || ', DEPT: ' || DEPT_NAME);
    CALL DBMS_OUTPUT.PUT_LINE('JOB: ' || JOB || ', MIN_SALARY: ' || MIN_SALARY || ', MAX_SALARY: ' || MAX_SALARY);
    CALL DBMS_OUTPUT.PUT_LINE('JOB HISTORY:');
    FOR J AS J1 CURSOR FOR (SELECT * FROM JOB_HISTORY WHERE EMPLOYEE_ID = EMP_ID)
        DO
            CALL DBMS_OUTPUT.PUT_LINE('JOB_ID: ' || J.JOB_ID || ', FROM: ' || J.START_DATE || ', TO: ' || J.END_DATE);
        end FOR;

    CALL DBMS_OUTPUT.PUT_LINE('COLLEAGUES WITH HIGHER INCOME:');
    FOR E AS E1 CURSOR FOR (SELECT (FIRST_NAME || ' ' || LAST_NAME) AS FULL_NAME, SALARY
                            FROM EMPLOYEES E
                            WHERE E.EMPLOYEE_ID != EMP_ID
                              AND E.DEPARTMENT_ID = DEPT_ID
                              AND SALARY > EMP_SALARY)
        DO
            CALL DBMS_OUTPUT.PUT_LINE('NAME: ' || E.FULL_NAME || ', SALARY: ' || E.SALARY);
        end for;
end;

BEGIN
    CALL FN24_3MI0700035.GET_EMP_INFO(101);
end;