SET SCHEMA FN24_3MI0700035;

CREATE OR REPLACE MODULE HW1;

ALTER MODULE HW1 PUBLISH FUNCTION FULL_NAME(ID INT)
    RETURNS VARCHAR(64);

ALTER MODULE HW1 ADD FUNCTION FULL_NAME(ID INT)
    RETURNS VARCHAR(64)
RETURN (SELECT (E.FIRST_NAME || ' ' || E.LAST_NAME) AS FULL_NAME
        FROM DB2HR.EMPLOYEES E
        WHERE E.EMPLOYEE_ID = ID);

VALUES (FN24_3MI0700035.HW1.FULL_NAME(100));

ALTER MODULE HW1 PUBLISH PROCEDURE DEPT_INFO(IN DEPT_ID INT);
ALTER MODULE HW1 ADD PROCEDURE DEPT_INFO(IN DEPT_ID INT)
BEGIN
    DECLARE BOSS_NAME VARCHAR(64);
    DECLARE MANAGER_ID INT;
    DECLARE DEPT_NAME VARCHAR(30);
    DECLARE MANAGER_COUNT INT;
    SET (MANAGER_ID, DEPT_NAME) =
            (SELECT D.MANAGER_ID, D.DEPARTMENT_NAME
             FROM DB2HR.DEPARTMENTS D
             WHERE D.DEPARTMENT_ID = DEPT_ID);
    SET BOSS_NAME = COALESCE(FN24_3MI0700035.HW1.FULL_NAME(MANAGER_ID), VARCHAR('NO MANAGER', 64));
    SET MANAGER_COUNT = (SELECT COUNT(*)
                         FROM DB2HR.EMPLOYEES
                         WHERE (JOB_ID LIKE '%MAN%'
                             OR JOB_ID LIKE '%MGR%')
                           AND DEPARTMENT_ID = DEPT_ID);
    CALL DBMS_OUTPUT.PUT_LINE('DEPT: ' || DEPT_NAME);
    CALL DBMS_OUTPUT.PUT_LINE('BOSS: ' || BOSS_NAME);
    CALL DBMS_OUTPUT.PUT_LINE('MANAGER_COUNT: ' || MANAGER_COUNT);
end;

BEGIN
    CALL FN24_3MI0700035.HW1.DEPT_INFO(50);
end;