SET SCHEMA FN24_3MI0700035;

-- T01
CREATE MODULE MOD3;

ALTER MODULE MOD3 PUBLISH PROCEDURE GET_COUNTRY(IN ID CHAR(2))
    LANGUAGE SQL
BEGIN
    DECLARE COUNTRY VARCHAR(64);
    SET COUNTRY =
            (SELECT COUNTRY_NAME
             FROM DB2HR.COUNTRIES
             WHERE COUNTRY_ID = ID);
    CALL DBMS_OUTPUT.PUT_LINE('Country: ' || COUNTRY);

end;

begin
    CALL FN24_3MI0700035.MOD3.GET_COUNTRY('AR');
end;

-- T02
ALTER MODULE MOD3 DROP PROCEDURE GET_REGION_SIZE( INTEGER);
ALTER MODULE MOD3 PUBLISH PROCEDURE GET_REGION_SIZE(IN ID INTEGER)
    LANGUAGE SQL
BEGIN
    DECLARE REGION VARCHAR(64);
    DECLARE SIZE INTEGER;
    SET (REGION, SIZE) =
            (SELECT R.REGION_NAME, COUNT(C.COUNTRY_ID)
             FROM DB2HR.COUNTRIES C
                      JOIN DB2HR.REGIONS R ON R.REGION_ID = C.REGION_ID

             WHERE R.REGION_ID = ID
             GROUP BY R.REGION_ID, R.REGION_NAME);
    CALL DBMS_OUTPUT.PUT_LINE('Region: ' || REGION || ' Size: ' || SIZE);

end;



BEGIN
    CALL FN24_3MI0700035.MOD3.GET_REGION_SIZE(2);
end;

-- T03
ALTER MODULE MOD3 DROP FUNCTION AVG_SALARY_DEPT(INT);
ALTER MODULE MOD3 PUBLISH FUNCTION AVG_SALARY_DEPT(DEPT INT)
    LANGUAGE SQL
    RETURNS DEC
BEGIN
    RETURN (SELECT DEC(AVG(E.SALARY), 10, 2)
            FROM DB2HR.EMPLOYEES E
            WHERE E.DEPARTMENT_ID = DEPT
            GROUP BY E.DEPARTMENT_ID);
end;

ALTER MODULE MOD3 PUBLISH PROCEDURE DEPT_INFO(IN DEPT INT)
    LANGUAGE SQL
BEGIN
    DECLARE NAME VARCHAR(30);
    DECLARE MIN_SAL DEC;
    DECLARE MAX_SAL DEC;
    DECLARE AVG_SAL DEC;
    SET (NAME, MIN_SAL, MAX_SAL, AVG_SAL) =
            (SELECT D.DEPARTMENT_NAME, MIN(E.SALARY), MAX(E.SALARY), DEC(AVG(E.SALARY), 10, 2)
             FROM DB2HR.EMPLOYEES E
                      JOIN DB2HR.DEPARTMENTS D on D.DEPARTMENT_ID = E.DEPARTMENT_ID
             WHERE E.DEPARTMENT_ID = DEPT
               AND E.SALARY > FN24_3MI0700035.MOD3.AVG_SALARY_DEPT(DEPT)
             GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME);

    CALL DBMS_OUTPUT.PUT_LINE('NAME: ' || NAME || ' MIN: ' || MIN_SAL || ' MAX: ' || MAX_SAL || ' AVG: ' || AVG_SAL);

end;

BEGIN
    CALL FN24_3MI0700035.MOD3.DEPT_INFO(50);
end;
SELECT * FROM DB2HR.DEPARTMENTS;