SET SCHEMA DB2SAMPLE;

-- ROLLUP (GROUP BY 1, GROUP BY 1, 2, GROUP BY 1, 2, 3, NO GROUP BY)

SELECT WORKDEPT, SEX, GROUPING(WORKDEPT) AS GW, GROUPING(SEX) AS GS,
       MIN(SALARY) AS MIN_SAL
FROM EMP
GROUP BY ROLLUP(WORKDEPT, SEX)
ORDER BY WORKDEPT;

-- CUBE (GROUP BY 1, GROUP BY 2, GROUP BY 1, 2, NO GROUP BY)
SELECT WORKDEPT, SEX, EDLEVEL,  MIN(SALARY) AS MIN_SAL,
       GROUPING(WORKDEPT) GW, GROUPING(SEX) GS, GROUPING(EDLEVEL) GE
FROM EMP
WHERE WORKDEPT IN ('C01', 'D11', 'A00')
GROUP BY CUBE(WORKDEPT, SEX, EDLEVEL)
ORDER BY WORKDEPT, SEX, EDLEVEL;


-- GROUPING SETS (GROUP BY 1, GROUP BY 2, GROUP BY 3)
SELECT WORKDEPT, SEX, EDLEVEL,  MIN(SALARY) AS MIN_SAL,
       GROUPING(WORKDEPT) GW, GROUPING(SEX) GS, GROUPING(EDLEVEL) GE
FROM EMP
WHERE WORKDEPT IN ('C01', 'D11', 'A00')
GROUP BY GROUPING SETS (WORKDEPT, SEX, EDLEVEL)
ORDER BY WORKDEPT, SEX, EDLEVEL;


SELECT NULL, NULL, MIN(SALARY) AS MIN_SAL
FROM EMP
UNION ALL
SELECT WORKDEPT, NULL, MIN(SALARY)
FROM EMP
GROUP BY WORKDEPT
UNION ALL
SELECT WORKDEPT, SEX, MIN(SALARY)
FROM EMP
GROUP BY WORKDEPT, SEX
ORDER BY 1, 2;


SELECT EMPNO, LASTNAME, SALARY, RANK() OVER (ORDER BY SALARY DESC) AS RANK
FROM EMP
WHERE WORKDEPT = 'C01';

CREATE OR REPLACE VIEW V_EMP_RANK_BY_HIREDATE
AS
SELECT EMPNO, LASTNAME, SALARY,
       BIRTHDATE, HIREDATE, RANK() OVER (ORDER BY YEAR(HIREDATE)) AS RANK
FROM EMP
WHERE WORKDEPT = 'C01';


SELECT *
FROM V_EMP_RANK_BY_HIREDATE
WHERE RANK = 1;

UPDATE EMP
SET SALARY = 1.1*SALARY
WHERE EMPNO = (
                SELECT EMPNO
                FROM V_EMP_RANK_BY_HIREDATE
                WHERE RANK = 1
               );

/* Problem 3
every department that appears in the EMPLOYEE table,
provided that the department has more than five employees. The report needs to
show the department number, the minimum, maximum, and average yearly salary,
and the number of employees who work in the department.
 */

    SELECT WORKDEPT, COUNT(*) AS EMP_CNT, MIN(SALARY) AS MIN_SAL, MAX(SALARY) AS MAX_SAL,
           DECIMAL(AVG(SALARY), 9, 2) AS AVG_SAL
    FROM EMP
    GROUP BY WORKDEPT
    HAVING COUNT(*) > 5;

/* Problem 4
 grouped by department, grouped by sex and in addition by the combination of
department and sex. List only
those who work in a department which start with the letter D.
List the department, the sex, sum of the salaries, minimum salary and maximum
salary.
*/
SELECT *
FROM
    (SELECT WORKDEPT, SEX, SUM(SALARY) AS SUMSAL, MIN(SALARY) AS MINSAL,
           MAX(SALARY) AS MAXSAL, GROUPING(WORKDEPT) GW, GROUPING(SEX) GS
    FROM EMP
    WHERE WORKDEPT LIKE 'D%'
    GROUP BY CUBE(WORKDEPT, SEX)
    ORDER BY WORKDEPT) R
WHERE NOT(R.GW=1 AND R.GS=1);

/*Problem 5
Joe's manager wants information about the average total salary for all departments.
List in department order, the department, average total salary and rank over the
average total salary.
 */

SELECT WORKDEPT, DECIMAL(AVG(SALARY), 9,2) AS AVGSAL,
       RANK() OVER(ORDER BY AVG(SALARY) DESC)
FROM EMP
GROUP BY WORKDEPT;

-- SUBQUERY


    SELECT * FROM DEPT
    WHERE DEPTNO NOT IN (SELECT WORKDEPT FROM EMP);

    SELECT * FROM DEPT
    WHERE DEPTNO NOT IN (SELECT WORKDEPT FROM EMP WHERE WORKDEPT IS NOT NULL);

    SELECT * FROM DEPT
    WHERE DEPTNO NOT IN (SELECT COALESCE(WORKDEPT, '000')
                         FROM EMP);

SELECT WORKDEPT, SUM(SALARY)
FROM EMP
WHERE WORKDEPT IS NOT NULL
GROUP BY WORKDEPT
HAVING SUM(SALARY) <= ALL (SELECT SUM(SALARY) FROM EMP WHERE WORKDEPT IS NOT NULL
                                                       GROUP BY WORKDEPT );