SET SCHEMA DB2SAMPLE;

-- T01
SELECT EMPNO, LASTNAME, WORKDEPT
FROM EMP
WHERE EMPNO NOT IN (SELECT EMPNO FROM EMPPROJACT);

-- T02
SELECT WORKDEPT, EMPNO, SALARY
FROM EMP E
WHERE SALARY > (SELECT AVG(SALARY)
                FROM EMP
                WHERE E.WORKDEPT = EMP.WORKDEPT)
ORDER BY WORKDEPT, EMPNO;

-- T03
SELECT WORKDEPT
FROM EMP
WHERE WORKDEPT != 'A00'
GROUP BY WORKDEPT
HAVING COUNT(EMPNO) = (SELECT COUNT(E.EMPNO)
                       FROM EMP E
                       WHERE E.WORKDEPT = 'A00'
                       GROUP BY E.WORKDEPT);

-- T04
SELECT EMPNO, LASTNAME, SALARY, WORKDEPT
FROM EMP
WHERE WORKDEPT != 'D11'
  AND SALARY > ANY (SELECT E.SALARY
                    FROM EMP E
                    WHERE E.WORKDEPT = 'D11')
ORDER BY EMPNO;

-- T05
SELECT EMPNO, LASTNAME, SALARY, WORKDEPT
FROM EMP
WHERE WORKDEPT != 'D11'
  AND SALARY > ALL (SELECT E.SALARY
                    FROM EMP E
                    WHERE E.WORKDEPT = 'D11')
ORDER BY EMPNO;

-- T06
SELECT E.EMPNO, E.LASTNAME, COUNT(EPA.ACTNO)
FROM EMP E
         JOIN EMPPROJACT EPA ON EPA.EMPNO = E.EMPNO
group by E.LASTNAME, E.EMPNO;

-- T07
SELECT DISTINCT E.EMPNO, E.LASTNAME, EPA.ACTNO
FROM EMP E
         JOIN EMPPROJACT EPA ON EPA.EMPNO = E.EMPNO
WHERE YEAR(EPA.EMSTDATE) <= 2002
  AND YEAR(EPA.EMENDATE) >= 2002
GROUP BY  (E.LASTNAME, E.EMPNO, EPA.ACTNO)
;