SET SCHEMA DB2CTE;

WITH REC_STAFF(SUBEMPNO, SUBENAME, SUBEHIREDATE, MNGRNAME)
         AS (SELECT EMPNO, ENAME, EHIREDATE, MNAME
             FROM EMP
             WHERE MNAME = 'KWAN'
             UNION ALL
             SELECT ORIG.EMPNO,
                    ORIG.ENAME,
                    ORIG.EHIREDATE,
                    ORIG.MNAME
             FROM EMP AS ORIG,
                  REC_STAFF REC
             WHERE REC.SUBEMPNO = ORIG.MGRNO)

SELECT MNGRNAME, COUNT(*) AS SUB_EMPS
FROM REC_STAFF
GROUP BY MNGRNAME;

SELECT *
FROM FLIGHTS;

WITH REC_FLIGHTS(RPATH,RARIVAL, NFLIGHTS, RPRICE)
         AS (SELECT DEPARTURE || '->' || ARRIVAL,ARRIVAL, 1, PRICE
             FROM FLIGHTS
             WHERE DEPARTURE = 'NEW YORK'
             UNION ALL
             SELECT REC.RPATH || '->' ||
                    ORIG.ARRIVAL,ORIG.ARRIVAL,
                    REC.NFLIGHTS + 1,
                    REC.RPRICE + ORIG.PRICE
             FROM FLIGHTS ORIG,
                  REC_FLIGHTS REC
             WHERE REC.RARIVAL =  ORIG.DEPARTURE)
SELECT RPATH,NFLIGHTS,RPRICE
FROM REC_FLIGHTS;