SET SCHEMA DB2CTE;

WITH EMP_CTE (PATH, EMP_NAME,MGR_NAME)
AS
(
    SELECT MANAGER || '->' || EMPLOYEE, EMPLOYEE, MANAGER
    FROM EMP_MGR
    WHERE MANAGER = 'Bala'
    UNION ALL
    SELECT PATH || '->' || A.EMPLOYEE, A.EMPLOYEE, A.MANAGER
    FROM EMP_MGR A, EMP_CTE B
    WHERE A.MANAGER = B.EMP_NAME
)
SELECT PATH
FROM EMP_CTE
ORDER BY PATH;

SELECT * FROM FLIGHTS;

WITH CTE_FLIGHTS (PATH, DEPARTURE, ARRIVAL, PRICE, CNT)
AS
(
    SELECT DEPARTURE || '->' || ARRIVAL, DEPARTURE, ARRIVAL, PRICE, 0
    FROM FLIGHTS
    WHERE DEPARTURE = 'NEW YORK'
    UNION ALL
    SELECT REC.PATH || '->' || ORIG.ARRIVAL,
           ORIG.DEPARTURE, ORIG.ARRIVAL,
           REC.PRICE + ORIG.PRICE, REC.CNT + 1
    FROM FLIGHTS ORIG, CTE_FLIGHTS REC
    WHERE REC.ARRIVAL = ORIG.DEPARTURE
    AND   REC.CNT <= 2
)
SELECT PATH, PRICE FROM CTE_FLIGHTS;


WITH CTE_PATH_FT(PATH, DEPARTURE, ARRIVAL, FLIGHT, TRAIN, PRICE, CNT)
AS
(
    SELECT DEPARTURE || '->' || ARRIVAL, DEPARTURE, ARRIVAL, 1, 0, PRICE, 0
    FROM FLIGHTS
    WHERE DEPARTURE = 'CHICAGO'
    UNION ALL
    SELECT DEPARTURE || '_' || ARRIVAL, DEPARTURE, ARRIVAL, 0, 1, PRICE, 0
    FROM TRAINS
    WHERE DEPARTURE = 'CHICAGO'
    UNION ALL
    SELECT PATH || '->' || ORIG.ARRIVAL, ORIG.DEPARTURE,
           ORIG.ARRIVAL, REC.FLIGHT + 1, REC.TRAIN, REC.PRICE + ORIG.PRICE, REC.CNT + 1
    FROM FLIGHTS ORIG, CTE_PATH_FT REC
    WHERE REC.ARRIVAL = ORIG.DEPARTURE AND REC.CNT <= 5
    UNION ALL
    SELECT PATH || '_' || ORIG.ARRIVAL, ORIG.DEPARTURE,
           ORIG.ARRIVAL, REC.FLIGHT, REC.TRAIN + 1, REC.PRICE + ORIG.PRICE, REC.CNT + 1
    FROM TRAINS ORIG, CTE_PATH_FT REC
    WHERE REC.ARRIVAL = ORIG.DEPARTURE AND REC.CNT <= 5

)
SELECT PATH, FLIGHT, TRAIN, PRICE FROM CTE_PATH_FT