SET SCHEMA FN24_3MI0700035;

CREATE FUNCTION E_DEGREE(EDLEVEL SMALLINT)
    RETURNS CHAR(12)

    LANGUAGE SQL

BEGIN
    ATOMIC

    DECLARE DEGREE CHAR(12);

    IF EDLEVEL = 12 THEN
        SET DEGREE = 'HIGH';

    ELSE
        SET DEGREE = 'UNKNNOWN';

    END IF;

    RETURN DEGREE;

END;

VALUES FN24_3MI0700035.e_degree(SMALLINT(18));

SET SCHEMA DB2CTE;

SELECT *
FROM TRAINS;

WITH CTE_TRAINS_PATH(PATH, DEPARTURE, ARRIVAL, LINKS, PRICE)
         AS (SELECT DEPARTURE || '>' || ARRIVAL, DEPARTURE, ARRIVAL, 1, PRICE
             FROM TRAINS
             WHERE DEPARTURE = 'CHICAGO'
             UNION ALL
             SELECT REC.PATH || '>' || ORIG.ARRIVAL,
                    ORIG.DEPARTURE,
                    ORIG.ARRIVAL,
                    REC.LINKS + 1,
                    REC.PRICE + ORIG.PRICE
             FROM TRAINS ORIG,
                  CTE_TRAINS_PATH REC
             WHERE REC.ARRIVAL = ORIG.DEPARTURE)
SELECT PATH, LINKS, PRICE
FROM CTE_TRAINS_PATH
WHERE PATH LIKE '%HONG KONG'
  AND PRICE = (SELECT MIN(PRICE)
               FROM CTE_TRAINS_PATH
               WHERE PATH LIKE '%HONG KONG');